component:
  one:
    name: service-one
    namespace: app-namespace-one
    # target endpoint for http client calls
    clientTarget: "http://{{ tpl .Values.component.two.name . }}.{{ tpl .Values.component.two.namespace . }}:8080/server-client"
  two:
    name: service-two
    namespace: app-namespace-two
    # target endpoint for http client calls
    clientTarget: "http://{{ tpl .Values.component.three.name . }}.{{ tpl .Values.component.three.namespace . }}:8080/server-client"
  three:
    name: service-three
    namespace: app-namespace-three
    # target endpoint for http  client calls
    clientTarget: "http://{{ tpl .Values.component.one.name . }}.{{ tpl .Values.component.one.namespace . }}:8080/server"

image:
  repository: romanfurst/client-server-sample
  pullPolicy: IfNotPresent
  tag: "1.0.0"

imagePullSecrets:
  - name: cn-system-image-pull-secret


